name             'zoo_workstation'
maintainer       'David Goerger'
maintainer_email 'david.goerger@yale.edu'
source_url       'https://github.com/dgoerger/zoo_workstation'
issues_url       'https://github.com/dgoerger/zoo_workstation/issues'
description      'Fedora Workstation'
long_description 'Configures Fedora Workstation for general computer lab use.'
license          'MIT'
supports         'fedora'
version          '2.0.7'
